name: start
run-name: start_flow

on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set env variable
        run: echo "MY_VAR=hello" >> $GITHUB_ENV

      - name: print env variable
        run: echo "$MY_VAR"
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print env variable
        run: echo "$MY_VAR"

